package scanner

const (
	TOKEN_KIND_EOF = iota
	TOKEN_KIND_LPAREN
	TOKEN_KIND_RPAREN
	TOKEN_KIND_LBRACE
	TOKEN_KIND_RBRACE
	TOKEN_KIND_COMMA
	TOKEN_KIND_SEMICOLON
	TOKEN_KIND_EQ
	TOKEN_KIND_PLUS
	TOKEN_KIND_MINUS
	TOKEN_KIND_STAR
	TOKEN_KIND_SLASH
	TOKEN_KIND_PERCENT
	TOKEN_KIND_BANG
	TOKEN_KIND_INT_LITERAL
	TOKEN_KIND_FLOAT_LITERAL
	TOKEN_KIND_CONST_KW
	TOKEN_KIND_FLOAT_KW
	TOKEN_KIND_FUNC_KW
	TOKEN_KIND_INT_KW
	TOKEN_KIND_RETURN_KW
	TOKEN_KIND_VAR_KW
	TOKEN_KIND_IDENT
)

type Token struct {
	Kind int
	Text *string
	Line int
	Col  int
}
