
name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building
      run: ${{ github.workspace }}/build.sh
    - name: Testing
      run: ${{ github.workspace }}/test.sh
