
name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building
      run: ${{ github.workspace }}\build.bat
    - name: Testing
      run: ${{ github.workspace }}\test.bat
